global using System.Security.Claims;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Http;
global using Newtonsoft.Json;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using Microsoft.Extensions.Logging;
global using Phoenix.Modules.MentalHealthTools.Data;
global using Phoenix.Shared.Business;
global using Phoenix.Shared.Business.Helpers;
global using OneOf;
