global using System.Text.Json;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Logging;
global using Phoenix.Auth.Business.Authentication;
global using Phoenix.Modules.Auth.Data;
global using OneOf;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Controller = Phoenix.Shared.Business.Controller;
global using Microsoft.EntityFrameworkCore;
global using Phoenix.Modules.Auth.Data.DataContext;
global using Phoenix.Shared.Business.Exceptionss;
